# SQLite version 3.x
# gem install sqlite3-ruby (not necessary on OS X Leopard)
# socket: /var/run/mysqld/mysqld.sock
development:
  adapter: mysql2
  encoding: utf8
  database: paperclip_sample_app_development
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock